### ISSUE TITLE
Can't get this working

### ISSUE THREAD

**Issue by lebagvondouche** [soxfor/qbittorrent-natmap#3]
Hi, not sure what I'm doing wrong but can't get this working:

```
2023-03-28 19:24:46 | Unable to grab VPN Public IP. Please check configuration
``` 

https://pastebin.com/rWMRug8R (compose file)

/cheers

**Comment by pvanryn** [comment]
Have you tried it with wireguard?  My gateway address looks like soxfor's example: **10.2.0.2/32**
Does gluetun get a public ip?
For whatever its worth, I have Qbit and Gluetun in a stack, with natmap running separately.

**Comment by soxfor** [comment]
> Hi, not sure what I'm doing wrong but can't get this working:
> 
> ```
> 2023-03-28 19:24:46 | Unable to grab VPN Public IP. Please check configuration
> ```
> 
> https://pastebin.com/rWMRug8R (compose file)
> 
> /cheers

Hi @lebagvondouche 

I see you're using openvpn, but that shouldn't be an issue (as long as it has the tun interface as well).

If that IP (10.16.0.5) is the actual tun0 gateway addr try setting it in the docker-compose without the CIDR notation

Change
- VPN_GATEWAY=10.16.0.5/16
To
- VPN_GATEWAY=10.16.0.5

**Comment by soxfor** [comment]
I'll look into it, I was remembered by another user on Reddit that OpenVPN is getting that IP dynamically, so I'll try and find a way to get that IP from the GW programmatically.

The IP you see there on the tun0 will be it's IP addr not the tun0 gw one 

Thank you for your report

**Comment by soxfor** [comment]
Hi @lebagvondouche 

I've just tested current version (1.1.0) with the qbittorrent-nox:latest image, and it worked.

Can you please revalidate on your end?

> docker ps -a | grep -E 'qbittorrent|gluetun'
259e9e9adf99   qbittorrentofficial/qbittorrent-nox:latest   "/sbin/tini -g -- /e…"   3 minutes ago   Up 3 minutes                                                                                                    qbt-ovpn
2aa3d4b750b5   ghcr.io/soxfor/qbittorrent-natmap:latest      "./start.sh"             5 minutes ago   Up 2 minutes                                                                                                    qbt-ovpn-natmap
8876adfa6368   ghcr.io/qdm12/gluetun:latest                 "/gluetun-entrypoint"    5 minutes ago   Up 5 minutes (healthy)      8000/tcp, 8388/tcp, 8888/tcp, 0.0.0.0:8080->8080/tcp, :::8080->8080/tcp, 8388/udp   vpn-ovpn

> docker logs qbt-ovpn
WebUI will be started shortly after internal preparations. Please wait...

> docker logs qbt-ovpn-natmap | tail -10
2023-05-06 23:32:05 | VPN container vpn-ovpn in healthy state!
2023-05-06 23:32:10 | qBittorrent SessionID Ok!
2023-05-06 23:32:10 | Public IP: <redacted>
2023-05-06 23:32:10 | Configured Port: 6881
2023-05-06 23:32:10 | Active Port: 45521
2023-05-06 23:32:10 | IPTables rule deleted for port 6881 on vpn-ovpn container
2023-05-06 23:32:10 | Port Changed to: 45521
2023-05-06 23:32:11 | IPTables rule added for port 45521 on vpn-ovpn container
2023-05-06 23:32:11 | NAT-PMP/UPnP Ok!
2023-05-06 23:32:11 | Sleeping for 5 minutes

![image](https://user-images.githubusercontent.com/7237915/236649190-cd3faeb5-4638-491b-a71c-12a5a141e9cc.png)
